// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO3RPWljujxY7vtzarTZDDRLD6NUIB2Uw',
    appId: '1:591527757296:web:1ccc3b05d0aa96b2a94935',
    messagingSenderId: '591527757296',
    projectId: 'flutter-instagram-5ed29',
    authDomain: 'flutter-instagram-5ed29.firebaseapp.com',
    storageBucket: 'flutter-instagram-5ed29.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0UVt3LjWLrXXCq9DAjykId227_Q3L9EQ',
    appId: '1:591527757296:android:562b7216da53a551a94935',
    messagingSenderId: '591527757296',
    projectId: 'flutter-instagram-5ed29',
    storageBucket: 'flutter-instagram-5ed29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5vA1JvAjC-8Lm5lMV5WImVuojc6O79GQ',
    appId: '1:591527757296:ios:04dfe14fed2be864a94935',
    messagingSenderId: '591527757296',
    projectId: 'flutter-instagram-5ed29',
    storageBucket: 'flutter-instagram-5ed29.appspot.com',
    iosBundleId: 'com.example.instagramFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5vA1JvAjC-8Lm5lMV5WImVuojc6O79GQ',
    appId: '1:591527757296:ios:04dfe14fed2be864a94935',
    messagingSenderId: '591527757296',
    projectId: 'flutter-instagram-5ed29',
    storageBucket: 'flutter-instagram-5ed29.appspot.com',
    iosBundleId: 'com.example.instagramFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO3RPWljujxY7vtzarTZDDRLD6NUIB2Uw',
    appId: '1:591527757296:web:3ce138ed5921d216a94935',
    messagingSenderId: '591527757296',
    projectId: 'flutter-instagram-5ed29',
    authDomain: 'flutter-instagram-5ed29.firebaseapp.com',
    storageBucket: 'flutter-instagram-5ed29.appspot.com',
  );
}
